### ISSUE TITLE
Vue support

### ISSUE THREAD

**Issue by stcroppe** [thekalinga/bootstrap4-vscode#10] opened 2017-07-13 07:49 UTC
Is it possible to provide Vue Template support for this vac extension?

**Comment by thekalinga** [comment] 2017-07-18 09:30
I have published a newer version of plugin. Please verify

**Comment by shilik** [comment] 2017-07-27 02:11
I tried, it doesn't work for .vue file.

**Comment by FetzenRndy** [comment] 2017-10-23 11:29
Vue template Support is added in my PR just needs to be merged... Also this plugin isnt of any use atm since it only Supports the bootstrap 4 alpha and is not compatible with the beta...

**Comment by FetzenRndy** [comment] 2017-10-23 11:30
Vue template Support is added in my PR just needs to be merged... Also this plugin isnt of any use atm since it only Supports the bootstrap 4 alpha and is not compatible with the beta...

**Comment by timster** [comment] 2018-01-29 16:01
This doesn't seem to work for me.

Completions work outside the template block, but not in it. I think the problem is that the extension is registered to work with `vue` filetype and not `vue-html`.

I manually updated my install of the extension to get it working.

Added the following in the `snippets` section.

    {
      "language": "vue-html",
      "path": "./snippets.json"
    }

**Comment by resting** [comment] 2018-08-01 07:11
@timster where do I find this `snippets` section?

**Comment by thekalinga** [comment] 2018-11-20 07:34
Fixed in version 5.0.0. Please check & let me know if there are any issues

**Closed by thekalinga** 2018-11-20 07:34 UTC
